# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
PYTHON_BLACK_CONFIG_FILE: .python-black
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: templates/
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: templates/
DISABLE_LINTERS:
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_GIT_DIFF
  - REPOSITORY_TRIVY
  - REPOSITORY_DEVSKIM
  - REPOSITORY_CHECKOV
  - CSS_STYLELINT
DISABLE:
  - COPYPASTE
  - SPELL

PRE_COMMANDS:
  - command: apk add py3-numpy py3-pandas && export PYTHONPATH=/usr/lib/python3.11/site-packages:/usr/lib/python3.10/site-packages && python -m pip install fastapi psycopg2_binary pydantic SQLAlchemy uvicorn
    cwd: "workspace"
  - command: apk add py3-numpy py3-pandas && export PYTHONPATH=/usr/lib/python3.11/site-packages && python -m pip install commentjson gitpython importlib-metadata jsonpickle multiprocessing_logging pychalk pygithub pytablewriter python-gitlab pyyaml regex terminaltables fastapi psycopg2_binary pydantic SQLAlchemy uvicorn
    venv: pylint
    cwd: "workspace"
