Application = "GLOBAL.ortelius.saas.ortelius"
Application_Version = "10.0.0"

Name = "GLOBAL.ortelius.saas.ms-scorecard"
Variant = "${BRANCH_NAME}"
Version = "v10.0.0.${BUILDNUM}-g${SHORT_SHA}"

[Export]
     IMAGE_TAG = "${Variant}-${Version}"
     COMPONENT_DOCKERREPO="${DockerRepo}"

[Attributes]
     BuildId = "${BUILD_ID}"
     BuildUrl = "https://console.cloud.google.com/cloud-build/builds/${BUILD_ID}?project=${PROJECT_ID}"
     Chart = "chart/ms-scorecard"
     ChartNameSpace = "ortelius"
     CustomAction = "GLOBAL.ArgoHelmAction"
     DockerBuildDate = "${BLDDATE}"
     DockerRepo = "quay.io/ortelius/ms-scorecard"
     DockerSha = "${DIGEST}"
     DockerTag = "${IMAGE_TAG}"
     GitCommit = "${SHORT_SHA}"
     License = "/workspace/LICENSE"
     Readme = "/workspace/README.md"
     ServiceOwner = "GLOBAL.Santa Fe Software.ETaylor"
     ArgoGitRepo = "git@github.com:ortelius/ortelius-ms-scorecard.git"
     ArgoGitBranch = "${GitBranch}"
     HelmValues = "chart/ms-scorecard/values.yaml"
     DeployAlways = "Y"
